<?php

declare(strict_types=1);

namespace App\Modules\Controllers\Articles;

use App\Modules\Controllers\AdminController;
use App\Modules\Entities\Article;
use App\Modules\Repositories\ArticleRepository;
use App\Services\CloudinaryService;
use App\Core\Database;

/**
 * CreateArticleController - Article Creation for Administrators
 *
 * Handles the creation of new articles with image upload to Cloudinary.
 * Only accessible to users with BDE (admin) status.
 *
 * Refactored to use Data Mapper pattern with Article entities and ArticleRepository.
 *
 * Features:
 * - Article form display
 * - Form validation (CSRF, required fields)
 * - Single image upload to Cloudinary
 * - Article data persistence via repository
 * - Success/error feedback with flash messages
 *
 * @package App\Modules\Controllers\Articles
 * @version 2.0.0 - Data Mapper refactoring
 * @author BdeLive Team
 *
 * @see AdminController For admin authentication requirements
 * @see ArticleRepository For database operations
 * @see CloudinaryService For image upload handling
 */
class CreateArticleController extends AdminController
{
    /**
     * Constructor - Handle article creation form display and submission
     *
     * GET request: Displays the article creation form
     * POST request with action=submitArticle: Processes the form submission
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();

        $action = $this->request->get('action', '');
        if ($this->request->isPost() && $action === 'submitArticle') {
            $this->createArticle();
        } else {
            $this->render('articles/createArticleView');
        }
    }

    /**
     * Create a new article
     *
     * Validates form data, uploads image to Cloudinary, and saves article to database.
     * Redirects back to form on validation error or to home on success.
     *
     * Required form fields:
     * - article-title: Article title
     * - article-description: Article content/description
     * - author: Author's full name
     * - article-image: Image file (uploaded to Cloudinary)
     *
     * @return void Redirects to appropriate page with flash message
     */
    private function createArticle(): void
    {
        // Validate CSRF token
        $csrfToken = $this->request->post('csrf_token', '');

        if (!$this->csrf->validateToken((string) $csrfToken)) {
            $this->setError('Token de sécurité invalide. Veuillez réessayer.');
            $this->redirect('index.php?page=createArticle');
        }

        // Get form data using Request object (not superglobals)
        $title = (string) $this->request->post('article-title', '');
        $description = (string) $this->request->post('article-description', '');

        // Validate required fields
        if (empty($title) || empty($description)) {
            $this->setError('Tous les champs sont obligatoires.');
            $this->redirect('index.php?page=createArticle');
        }

        // Admin/superadmin qui publie (nom automatique depuis la session)
        $userId = $this->auth->getUserId();
        $firstName = $this->auth->getUserFirstName() ?? '';
        $lastName = $this->auth->getUserLastName() ?? '';
        $author = trim($firstName . ' ' . $lastName);
        if ($author === '') {
            $author = 'BDE';
        }

        // Upload image to Cloudinary (optionnel)
        $imageUrl = '';
        $file = $this->request->file('article-image');

        // Upload seulement si une image est fournie
        if ($file !== null && !empty($file['name']) && !empty($file['tmp_name'])) {
            try {
                $cloudinary = new CloudinaryService();
                /** @var array{name: string, type: string, tmp_name: string, error: int, size: int} $file */
                $uploadedImage = $cloudinary->uploadImage($file, 'articles');

                if ($uploadedImage === null) {
                    error_log('CreateArticleController::createArticle - Image upload failed');
                    $this->setError('Erreur lors de l\'upload de l\'image. Veuillez réessayer.');
                    $this->redirect('index.php?page=createArticle');
                }

                $imageUrl = $uploadedImage['url'];
            } catch (\Exception $e) {
                error_log('CreateArticleController::createArticle - Cloudinary error: ' . $e->getMessage());
                $this->setError('Erreur lors de l\'upload de l\'image. Veuillez réessayer.');
                $this->redirect('index.php?page=createArticle');
            }
        }

        // Create Article entity (id = null for new article, slug will be generated by repository)
        // admin_creator = user_id de l'admin connecté (affiché "publié par Prénom Nom")
        $article = new Article(
            id: null,
            title: $title,
            slug: '', // Will be generated by repository
            description: $description,
            imageUrl: !empty($imageUrl) ? $imageUrl : null,
            author: $author,
            createdAt: date('Y-m-d H:i:s'),
            adminCreatorId: $userId,
            publisherName: $author
        );

        // Save via repository (will detect insert because id is null)
        $repository = new ArticleRepository(Database::getInstance()->getConnection());
        $result = $repository->save($article);

        if ($result) {
            $this->setSuccess('Article créé avec succès.');
            $this->redirect('index.php?page=home');
        } else {
            $this->setError('Une erreur est survenue lors de la création de l\'article.');
            $this->redirect('index.php?page=createArticle');
        }
    }
}
